### ISSUE TITLE
Avazbek

### ISSUE THREAD

**Issue by Sardoralgoritm** [BroOverflowbugs/UPG#9]
Avazbek visual dan push qibsiz lekin Pull request yaratmabsiz pull request yaratib qoyin uka

**Comment by AvazbekOlimov** [comment]
Aha ho'p bo'ladi

![image](https://github.com/BroOverflowbugs/UPG/assets/92303549/9e1e55f9-338f-4fac-8774-0ae5e7f58feb)

Mana aka
